import {
  BarChart3,
  Brain,
  ClipboardList,
  Code2,
  Database,
  DatabaseZap,
  DollarSign,
  FileText,
  Megaphone,
  Monitor,
  MousePointerClick,
  Move3D,
  Palette,
  PenTool,
  PieChart,
  Repeat,
  Server,
  Settings2,
  Smartphone
} from "lucide-react";
import type {JSX} from "react";
import React from "react";

export const categoryIconMap: Record<string, JSX.Element> = {
  development: React.createElement(Code2, {className: "h-5 w-5 text-purple-400"}),
  backend: React.createElement(Server, {className: "h-5 w-5 text-purple-400"}),
  frontend: React.createElement(Monitor, {className: "h-5 w-5 text-purple-400"}),
  mobile: React.createElement(Smartphone, {className: "h-5 w-5 text-purple-400"}),
  devops: React.createElement(Settings2, {className: "h-5 w-5 text-purple-400"}),
  data: React.createElement(Database, {className: "h-5 w-5 text-purple-400"}),
  data_analysis: React.createElement(BarChart3, {className: "h-5 w-5 text-purple-400"}),
  machine_learning: React.createElement(Brain, {className: "h-5 w-5 text-purple-400"}),
  data_engineering: React.createElement(DatabaseZap, {className: "h-5 w-5 text-purple-400"}),
  design: React.createElement(Palette, {className: "h-5 w-5 text-purple-400"}),
  ux_design: React.createElement(MousePointerClick, {className: "h-5 w-5 text-purple-400"}),
  ui_design: React.createElement(PenTool, {className: "h-5 w-5 text-purple-400"}),
  interaction_design: React.createElement(Move3D, {className: "h-5 w-5 text-purple-400"}),
  product_management: React.createElement(ClipboardList, {className: "h-5 w-5 text-purple-400"}),
  product_planning: React.createElement(FileText, {className: "h-5 w-5 text-purple-400"}),
  product_analysis: React.createElement(PieChart, {className: "h-5 w-5 text-purple-400"}),
  agile_methodology: React.createElement(Repeat, {className: "h-5 w-5 text-purple-400"}),
  marketing: React.createElement(Megaphone, {className: "h-5 w-5 text-purple-400"}),
  content_marketing: React.createElement(FileText, {className: "h-5 w-5 text-purple-400"}),
  advertising: React.createElement(DollarSign, {className: "h-5 w-5 text-purple-400"}),
  Backend: React.createElement(Code2, {className: "h-5 w-5 text-purple-400"}),
  Frontend: React.createElement(Palette, {className: "h-5 w-5 text-purple-400"}),
  "Data Science": React.createElement(BarChart3, {className: "h-5 w-5 text-purple-400"}),
  Database: React.createElement(Database, {className: "h-5 w-5 text-purple-400"}),
  Design: React.createElement(Palette, {className: "h-5 w-5 text-purple-400"}),
  default: React.createElement(Code2, {className: "h-5 w-5 text-purple-400"}),
}; 